// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTac5xzbk9VFAyviDP5AVstfUm7f8Mg3U',
    appId: '1:535427867658:web:e5d4a32dd368c48029ebf3',
    messagingSenderId: '535427867658',
    projectId: 'travel-app-d8e3c',
    authDomain: 'travel-app-d8e3c.firebaseapp.com',
    storageBucket: 'travel-app-d8e3c.firebasestorage.app',
    measurementId: 'G-3TH70L0XYP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6JQqd51L9z3SriF4MIzRAU6mDufHZ9X4',
    appId: '1:535427867658:android:41e8d932c20fd56029ebf3',
    messagingSenderId: '535427867658',
    projectId: 'travel-app-d8e3c',
    storageBucket: 'travel-app-d8e3c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw63RvLpvkdYLdGI9oLNsMsBPt1JX9jHI',
    appId: '1:535427867658:ios:244482bb43fb49ed29ebf3',
    messagingSenderId: '535427867658',
    projectId: 'travel-app-d8e3c',
    storageBucket: 'travel-app-d8e3c.firebasestorage.app',
    iosBundleId: 'com.example.temporalZodiac',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBw63RvLpvkdYLdGI9oLNsMsBPt1JX9jHI',
    appId: '1:535427867658:ios:244482bb43fb49ed29ebf3',
    messagingSenderId: '535427867658',
    projectId: 'travel-app-d8e3c',
    storageBucket: 'travel-app-d8e3c.firebasestorage.app',
    iosBundleId: 'com.example.temporalZodiac',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTac5xzbk9VFAyviDP5AVstfUm7f8Mg3U',
    appId: '1:535427867658:web:9767f7fe1871245029ebf3',
    messagingSenderId: '535427867658',
    projectId: 'travel-app-d8e3c',
    authDomain: 'travel-app-d8e3c.firebaseapp.com',
    storageBucket: 'travel-app-d8e3c.firebasestorage.app',
    measurementId: 'G-131QEMS9JE',
  );
}
